/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tango.gui;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;

/**
 *
 * @author Chantal
 */
public class TangoFrame extends javax.swing.JFrame {

    ExperimentPanel experimentpanel;
    JPanel south;
    /**
     * Creates new form TangoFrame
     */
    public TangoFrame() {
        initComponents();
        
        south = new JPanel();
        south.setLayout(new BorderLayout());
        experimentpanel = new ExperimentPanel(south);
        //this.split.add(JSplitPane.TOP, experimentpanel);
        this.setLayout(new BorderLayout());
        add("Center", experimentpanel);
        //this.split.add(JSplitPane.BOTTOM, south);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        menuNew = new javax.swing.JMenuItem();
        run = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenu();
        model = new javax.swing.JMenuItem();
        view = new javax.swing.JMenu();
        menuChart = new javax.swing.JMenuItem();
        menuCorr = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        menuHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        file.setText("File");

        menuNew.setText("New");
        menuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewActionPerformed(evt);
            }
        });
        file.add(menuNew);

        run.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/arrow-right.png"))); // NOI18N
        run.setText("Run Experiment");
        run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runActionPerformed(evt);
            }
        });
        file.add(run);

        menu.add(file);

        edit.setText("Edit");

        model.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/config.png"))); // NOI18N
        model.setText("Pick model");
        model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelActionPerformed(evt);
            }
        });
        edit.add(model);

        menu.add(edit);

        view.setText("View");

        menuChart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/flowdiagram.png"))); // NOI18N
        menuChart.setText("View chart");
        menuChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChartActionPerformed(evt);
            }
        });
        view.add(menuChart);

        menuCorr.setText("View correlations");
        menuCorr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCorrActionPerformed(evt);
            }
        });
        view.add(menuCorr);

        menu.add(view);

        help.setText("Help");

        menuHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/help-3.png"))); // NOI18N
        menuHelp.setText("Help");
        menuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHelpActionPerformed(evt);
            }
        });
        help.add(menuHelp);

        menu.add(help);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runActionPerformed
        experimentpanel.runExperiment();
    }//GEN-LAST:event_runActionPerformed

    private void menuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewActionPerformed
        experimentpanel.restart();
    }//GEN-LAST:event_menuNewActionPerformed

    private void menuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHelpActionPerformed
       experimentpanel.help();
    }//GEN-LAST:event_menuHelpActionPerformed

    private void modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelActionPerformed
        experimentpanel.pickModel();
    }//GEN-LAST:event_modelActionPerformed

    private void menuChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChartActionPerformed
        experimentpanel.showChart();
    }//GEN-LAST:event_menuChartActionPerformed

    private void menuCorrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCorrActionPerformed
        experimentpanel.showCorr();
    }//GEN-LAST:event_menuCorrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TangoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TangoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TangoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TangoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TangoFrame f = new TangoFrame();
                //f.setVisible(true);
                f.setSize(new Dimension(1100, 820));
                f.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu edit;
    private javax.swing.JMenu file;
    private javax.swing.JMenu help;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem menuChart;
    private javax.swing.JMenuItem menuCorr;
    private javax.swing.JMenuItem menuHelp;
    private javax.swing.JMenuItem menuNew;
    private javax.swing.JMenuItem model;
    private javax.swing.JMenuItem run;
    private javax.swing.JMenu view;
    // End of variables declaration//GEN-END:variables
}
